---
title: "EDA"
output: html_document
---

```{r, setup, echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(tidyverse)
dass_new = read.csv("./data/dass_new.csv")
```

```{r}
# distribution histogram of age
ggplot(dass_new, aes(x=age)) + 
    geom_histogram(binwidth=.5,
                  fill="#FF6666") 
```

```{r}


```





# Chi-squared Test 1
$H_0$: The proportion in different depression levels among age groups are equal. \
$H_1$: Not all proportions are equal.
```{r}
dass_chi <- dass_new|>
  # form age groups
  mutate(age = case_when(age <= 18 ~ "teenage", 
                         age <= 25 & age >18 ~ "young adult",
                         age <= 50 & age >25 ~ "adult", 
                         age >50 ~ "older"))
# show result table to perform chi-squared test
dass_chi|>
  group_by(age)|>
  summarise(Normal = sum(depression_level=="Normal"),
            Mild = sum(depression_level=="Mild"),
            Moderate = sum(depression_level=="Moderate"),
            Severe = sum(depression_level=="Severe"),
            Extremely_Severe = sum(depression_level=="Extremely severe"))
# perform chi-squared test
chisq.test(pull(dass_chi, age), pull(dass_chi, depression_level))|>
  broom::tidy()|>
  knitr::kable()
```