---
title: "Introduction"
output: html_document
---

# Motivation

Observing that mental health issues appear at a younger and younger age, we would like to test if DASS can potentially provide a means to objectively evaluate the severity and the potential factors of depression among different population including races, ages, etc.

# Related Work

In the realm of depression level research, the exploration of psychosocial determinants has been a prominent focus. [Melissa et. al](doi: 10.1016/j.chiabu.2017.03.016) delved into the impact of adverse childhood experiences on the prevalence of depression in adulthood, elucidating the long-term consequences of early-life stressors. Concurrently, the work of [Virginia et. al](doi: 10.1016/j.wombi.2020.12.014) the relationship between perceived social support and anxiety/depression in UK-based pregnant women during the COVID-19 pandemic. Furthermore, a meta-analysis by [Postmes et. al]( https://doi.org/10.1002/ejsp.2508) has systematically review and quantitatively analyze existing studies to examine the relationship between social identification and depression. Such interdisciplinary approaches contribute to a more comprehensive and nuanced comprehension of the factors influencing mental health and provide a foundation for tailored interventions and support mechanisms.

# Initial Questions

-   What factors have a significant impact on the level of depression?

-   Do different countries exhibit significantly varied rates of depression at different levels of development?

-   What factors account for the differences in the development of depression levels?

-   What factors can be used to predict depression levels?

# Introduction
Depression, a pervasive mental health challenge, is becoming increasingly prevalent among younger demographics, necessitating a deeper understanding of its existence in diverse populations. This study seeks to harness the potential of the Depression, Anxiety, and Stress Scales (DASS) as a comprehensive tool to objectively assess the severity and underlying factors influencing or contributing to depression across demographic groups, including differences in race, age groups, and more.

Our study utilizes an extensive dataset from the Depression, Anxiety, and Stress Scales (DASS) Responses accessible via Kaggle, to accomplish our objectives. This dataset includes 42 self-reported items, carefully created to evaluate emotional states associated with depression, anxiety, and stress. The objective of our project is to contribute to a more thorough comprehension of the determinants of depression, which could potentially inform customized support strategies and targeted interventions designed for specific population groups.

Our methodology involves filtering data, performing validity checks, and eliminating unreliable data to bolster the integrity of our analysis. We will then stratify individuals' depression levels and present their distributions across various variables using graphical representations, such as line charts. To compare factor distributions across different depression levels, we will employ statistical tools like the chi-squared test. Our study aims to employ logistic regression models to identify influential factors contributing to varying levels of depression, including age, gender, geographical location, and etc. Additionally, we plan to create data visualizations on coefficients and model fit after constructing the model.