---
title: "Statistical Analysis"
author: "Qin Huang"
date: "2023-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pheatmap)
```

```{r}
# Select the columns you need and create a data frame
dass_heat1 <- dass %>%
  dplyr::select(-matches('Q\\d+A')) %>%
  dplyr::select(-country)

# Calculate the correlation matrix

r <- cor(dass_heat1,
         method = "pearson",
         use = "pairwise.complete.obs"
) 

pheatmap(r, 
         show_colnames = TRUE,   
         show_rownames=TRUE,    
         fontsize=5,             
         color = colorRampPalette(c('#0000ff','#ffffff','#ff0000'))(100), 
         annotation_legend=TRUE, 
         border_color=NA,        
         scale="none",            
         cluster_rows = T,
         cluster_cols = T     
)

```

```{r}
dass_heat2 <- dass %>%
  mutate(
    depression = Q3A + Q5A + Q10A + Q13A + Q16A + Q17A + Q21A + Q24A + Q26A + Q31A + Q34A + Q37A + Q38A + Q42A - 14,
    anxiety = Q2A + Q4A + Q7A + Q9A + Q15A + Q19A + Q20A + Q23A + Q25A + Q28A + Q30A + Q36A + Q40A + Q41A - 14,
    stress = Q1A + Q6A + Q8A + Q11A + Q12A + Q14A + Q18A + Q22A + Q27A + Q29A + Q32A + Q33A + Q35A + Q39A - 14
    ) %>%
  mutate(depression = case_when(
    depression >= 0 & depression <= 9 ~ 0,
    depression >= 10 & depression <= 13 ~ 1,
    depression >= 14 & depression <= 20 ~ 2,
    depression >= 21 & depression <= 27 ~ 3,
    depression >= 28 ~ 4
  )) %>%
  mutate(anxiety = case_when(
    anxiety >= 0 & anxiety <= 7 ~ 0,
    anxiety >= 8 & anxiety <= 9 ~ 1,
    anxiety >= 10 & anxiety <= 14 ~ 2,
    anxiety >= 15 & anxiety <= 19 ~ 3,
    anxiety >= 20 ~ 4
  )) %>%
  mutate(stress = case_when(
    stress >= 0 & stress <= 14 ~ 0,
    stress >= 15 & stress <= 18 ~ 1,
    stress >= 19 & stress <= 25 ~ 2,
    stress >= 26 & stress <= 33 ~ 3,
    stress >= 34 ~ 4
  )) %>%
  dplyr::select(depression,anxiety,stress)

r1 <- cor(dass_heat2,
         method = "pearson",
         use = "pairwise.complete.obs"
) 

pheatmap(r1, 
         show_colnames = TRUE,   
         show_rownames=TRUE,    
         fontsize=5,             
         color = colorRampPalette(c('#ffffff','#ff0000'))(100), 
         annotation_legend=TRUE, 
         border_color=NA,        
         scale="none",            
         cluster_rows = F,
         cluster_cols = F,
         breaks = seq(0, 1, length.out = 90)
)
```
